import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("Seeding Jijau Computers database...");

  // 1. Website Settings
  await prisma.websiteSetting.upsert({
    where: { id: "default" },
    update: {},
    create: {
      id: "default",
      storeName: "Jijau Computers",
      tagline: "Your Tech Partner",
      logoUrl: "",
      darkLogoUrl: "",
      faviconUrl: "",
      primaryColor: "#2563eb", // Vibrant Royal Blue
      secondaryColor: "#f59e0b", // Amber Gold accent
      phone: "+91 88056 07908",
      whatsapp: "918805607908",
      email: "sales@jijaucomputers.in",
      address: "Shop No. 12 & 13, Jijau Plaza, Near Railway Station, Shivajinagar, Pune, Maharashtra 411005",
      googleMapsUrl: "https://maps.google.com/?q=Shivajinagar,Pune,Maharashtra",
      openingHours: "Mon - Sat: 10:00 AM - 9:00 PM | Sun: 11:00 AM - 6:00 PM",
      gstin: "27AABCJ1234F1Z9",
      upiId: "jijauc@ibl",
      upiName: "Jijau Computers",
      facebookUrl: "https://facebook.com/jijaucomputers",
      instagramUrl: "https://instagram.com/jijaucomputers",
      youtubeUrl: "https://youtube.com/jijaucomputers",
      linkedinUrl: "https://linkedin.com/company/jijaucomputers",
      metaTitle: "Jijau Computers - Premium Laptops, Gaming PCs & Hardware Store in Pune",
      metaDescription: "Explore the best deals on custom gaming PCs, laptops, graphics cards, processors, CCTV, and same-day repair services at Jijau Computers Pune.",
      metaKeywords: "jijau computers pune, gaming pc build pune, custom pc quote, laptops shop pune, graphic card rtx 4070, intel i7 processor, computer repair pune"
    },
  });

  // 2. Admin User
  await prisma.adminUser.upsert({
    where: { username: "admin" },
    update: {},
    create: {
      username: "admin",
      password: "adminpassword123",
      name: "Jijau Store Administrator",
      email: "admin@jijaucomputers.in",
      role: "SUPERADMIN",
    },
  });

  // 3. Brands
  const brandsData = [
    { name: "ASUS", slug: "asus", logoUrl: "https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=120&auto=format&fit=crop&q=80" },
    { name: "HP", slug: "hp", logoUrl: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=120&auto=format&fit=crop&q=80" },
    { name: "Dell", slug: "dell", logoUrl: "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=120&auto=format&fit=crop&q=80" },
    { name: "Lenovo", slug: "lenovo", logoUrl: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=120&auto=format&fit=crop&q=80" },
    { name: "Apple", slug: "apple", logoUrl: "https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=120&auto=format&fit=crop&q=80" },
    { name: "Samsung", slug: "samsung", logoUrl: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=120&auto=format&fit=crop&q=80" },
    { name: "OnePlus", slug: "oneplus", logoUrl: "https://images.unsplash.com/photo-1580910051074-3eb694886505?w=120&auto=format&fit=crop&q=80" },
    { name: "Xiaomi", slug: "xiaomi", logoUrl: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=120&auto=format&fit=crop&q=80" },
    { name: "Epson", slug: "epson", logoUrl: "https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=120&auto=format&fit=crop&q=80" },
    { name: "Canon", slug: "canon", logoUrl: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=120&auto=format&fit=crop&q=80" },
    { name: "Brother", slug: "brother", logoUrl: "https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=120&auto=format&fit=crop&q=80" },
    { name: "CP PLUS", slug: "cp-plus", logoUrl: "https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=120&auto=format&fit=crop&q=80" },
    { name: "Hikvision", slug: "hikvision", logoUrl: "https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=120&auto=format&fit=crop&q=80" },
    { name: "TP-Link", slug: "tp-link", logoUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=120&auto=format&fit=crop&q=80" },
    { name: "Intel", slug: "intel", logoUrl: "https://images.unsplash.com/photo-1555618568-9a3d4608c0ff?w=120&auto=format&fit=crop&q=80" },
    { name: "AMD", slug: "amd", logoUrl: "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=120&auto=format&fit=crop&q=80" },
    { name: "NVIDIA", slug: "nvidia", logoUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=120&auto=format&fit=crop&q=80" },
    { name: "MSI", slug: "msi", logoUrl: "https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=120&auto=format&fit=crop&q=80" },
    { name: "Corsair", slug: "corsair", logoUrl: "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=120&auto=format&fit=crop&q=80" },
    { name: "Logitech", slug: "logitech", logoUrl: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=120&auto=format&fit=crop&q=80" },
    { name: "Kingston", slug: "kingston", logoUrl: "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=120&auto=format&fit=crop&q=80" },
    { name: "Western Digital", slug: "western-digital", logoUrl: "https://images.unsplash.com/photo-1531492746076-161ca9bcad58?w=120&auto=format&fit=crop&q=80" },
  ];

  const brandMap = new Map<string, string>();
  for (const b of brandsData) {
    const brand = await prisma.brand.upsert({
      where: { slug: b.slug },
      update: { name: b.name, logoUrl: b.logoUrl },
      create: b,
    });
    brandMap.set(b.slug, brand.id);
  }

  // 4. Categories - Top 4 Stacks + Components
  const categoriesData = [
    { name: "Laptop", slug: "laptops", iconName: "Laptop", description: "Gaming, Ultrabooks, Business & Student Laptops", order: 1, imageUrl: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=400&auto=format&fit=crop&q=80" },
    { name: "Mobile", slug: "mobiles", iconName: "Smartphone", description: "5G Smartphones, Flagships, Gaming Phones & Tablets", order: 2, imageUrl: "https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=400&auto=format&fit=crop&q=80" },
    { name: "Printer", slug: "printers", iconName: "Printer", description: "Ink Tank, Laser, All-in-One Wireless Printers & Scanners", order: 3, imageUrl: "https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=400&auto=format&fit=crop&q=80" },
    { name: "CCTV Camera", slug: "cctv-camera", iconName: "Camera", description: "HD IP Cameras, ColorVu Night Vision, WiFi PTZ & NVRs", order: 4, imageUrl: "https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=400&auto=format&fit=crop&q=80" },
    { name: "Custom Gaming PCs", slug: "custom-gaming-pcs", iconName: "Cpu", description: "Extreme Performance custom liquid-cooled RGB Battle-stations", order: 5, imageUrl: "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=400&auto=format&fit=crop&q=80" },
    { name: "Processors (CPU)", slug: "processors", iconName: "Cpu", description: "Intel Core 14th Gen & AMD Ryzen 7000/9000 series", order: 6, imageUrl: "https://images.unsplash.com/photo-1555618568-9a3d4608c0ff?w=400&auto=format&fit=crop&q=80" },
    { name: "Graphics Cards (GPU)", slug: "graphics-cards", iconName: "Tv", description: "NVIDIA GeForce RTX 40 & AMD Radeon RX series", order: 7, imageUrl: "https://images.unsplash.com/photo-1591488320449-011701bb6704?w=400&auto=format&fit=crop&q=80" },
    { name: "Monitors", slug: "monitors", iconName: "Monitor", description: "High Refresh Rate 144Hz-240Hz Gaming & 4K IPS Displays", order: 8, imageUrl: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400&auto=format&fit=crop&q=80" },
  ];

  const categoryMap = new Map<string, string>();
  for (const c of categoriesData) {
    let cat = await prisma.category.findFirst({
      where: { OR: [{ slug: c.slug }, { name: c.name }] },
    });

    if (cat) {
      cat = await prisma.category.update({
        where: { id: cat.id },
        data: {
          name: c.name,
          slug: c.slug,
          order: c.order,
          description: c.description,
          iconName: c.iconName,
          imageUrl: c.imageUrl,
        },
      });
    } else {
      cat = await prisma.category.create({ data: c });
    }

    categoryMap.set(c.slug, cat.id);
  }

  // 5. Hero Banners
  const banners = [
    {
      title: "Jijau Custom Gaming Battlestations",
      subtitle: "Unleash Ultimate Power with Intel 14th Gen & RTX 4080 Super | Custom Liquid Cooling & Rig Tuning",
      tag: "FLAGSHIP PC BUILDS",
      imageUrl: "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=1400&auto=format&fit=crop&q=80",
      ctaText: "Configure Your PC",
      ctaLink: "/custom-pc",
      order: 1,
      isActive: true,
    },
    {
      title: "Mega Laptop Festival 2026",
      subtitle: "Up to ₹25,000 Off on ASUS ROG, HP OMEN, Lenovo Legion & Dell XPS + Free Gaming Bag & Mouse",
      tag: "FESTIVAL SPECIAL",
      imageUrl: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=1400&auto=format&fit=crop&q=80",
      ctaText: "Shop Laptop Deals",
      ctaLink: "/products?category=laptops",
      order: 2,
      isActive: true,
    },
    {
      title: "Next-Gen Graphics Cards In Stock",
      subtitle: "GeForce RTX 4090, 4080 Super & 4070 Ti Super at Genuine Pune Dealer Prices with Full Official Warranty",
      tag: "HARDWARE DEALS",
      imageUrl: "https://images.unsplash.com/photo-1591488320449-011701bb6704?w=1400&auto=format&fit=crop&q=80",
      ctaText: "View Graphics Cards",
      ctaLink: "/products?category=graphics-cards",
      order: 3,
      isActive: true,
    },
  ];

  for (const b of banners) {
    await prisma.banner.create({ data: b });
  }

  // 6. Offers & Coupons
  const offers = [
    {
      title: "Diwali & Festive Mega Sale",
      badge: "LIMITED TIME",
      description: "Flat ₹5,000 OFF on all custom PC builds over ₹75,000. Includes free cable management & Windows setup.",
      bannerUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&auto=format&fit=crop&q=80",
      discountPct: 15,
      couponCode: "JIJAUFEST",
      isActive: true,
    },
    {
      title: "Student Laptop Booster Deal",
      badge: "STUDENT SPECIAL",
      description: "Get instant ₹2,500 off + Free Premium Laptop Bag, Wireless Mouse, and Antivirus with any student laptop.",
      bannerUrl: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&auto=format&fit=crop&q=80",
      discountPct: 10,
      couponCode: "STUDENTPRO",
      isActive: true,
    },
    {
      title: "SSD & RAM Upgrade Supercombo",
      badge: "HOT DEAL",
      description: "Upgrade your old laptop or desktop with 1TB NVMe SSD + 16GB RAM with free onsite installation.",
      bannerUrl: "https://images.unsplash.com/photo-1562976540-1502c2145186?w=600&auto=format&fit=crop&q=80",
      discountPct: 20,
      couponCode: "SPEEDUP",
      isActive: true,
    },
  ];

  for (const o of offers) {
    await prisma.offer.create({ data: o });
  }

  // 7. Products
  const products = [
    {
      name: "ASUS ROG Strix G16 (2024) Gaming Laptop",
      slug: "asus-rog-strix-g16-gaming-laptop",
      sku: "ASUS-ROG-G16-4060",
      categorySlug: "laptops",
      brandSlug: "asus",
      price: 139990,
      salePrice: 124990,
      stock: 8,
      inStock: true,
      warranty: "2 Years ASUS On-Site International Warranty",
      isFeatured: true,
      isBestseller: true,
      isNewArrival: true,
      isTrending: true,
      isGamingDeal: true,
      shortDesc: "16-inch QHD+ 240Hz display, Intel Core i7-13650HX, 16GB DDR5, 1TB NVMe SSD, RTX 4060 8GB GDDR6.",
      description: "Conquer any AAA title and heavyweight creative workload with the ASUS ROG Strix G16. Powered by 13th Gen Intel Core i7 processor and NVIDIA GeForce RTX 4060 laptop GPU with Max TGP of 140W and MUX Switch with NVIDIA Advanced Optimus. Features ROG Intelligent Cooling with Tri-Fan technology and Conductonaut Extreme liquid metal.",
      specsJson: JSON.stringify({
        Processor: "Intel Core i7-13650HX (14 cores, up to 4.9 GHz)",
        Graphics: "NVIDIA GeForce RTX 4060 8GB GDDR6 (140W TGP)",
        Display: "16-inch QHD+ 240Hz 3ms IPS ROG Nebula Display 100% DCI-P3",
        Memory: "16GB DDR5-4800MHz (Expandable up to 64GB)",
        Storage: "1TB PCIe 4.0 NVMe M.2 SSD",
        Keyboard: "Per-Key RGB Backlit Chiclet Keyboard with Aura Sync",
        Weight: "2.50 Kg",
        OS: "Windows 11 Home + MS Office 2021 pre-installed",
      }),
      images: [
        "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=800&auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&auto=format&fit=crop&q=80",
      ],
    },
    {
      name: "Lenovo Legion Pro 5i Gen 9 Gaming Laptop",
      slug: "lenovo-legion-pro-5i-gen-9",
      sku: "LEN-LEG-PRO5-4070",
      categorySlug: "laptops",
      brandSlug: "lenovo",
      price: 178000,
      salePrice: 159990,
      stock: 5,
      inStock: true,
      warranty: "3 Years Lenovo Legion Ultimate Support + 1 Yr ADP",
      isFeatured: true,
      isBestseller: true,
      isNewArrival: true,
      isTrending: true,
      isGamingDeal: true,
      shortDesc: "Intel Core i9-14900HX, 32GB DDR5 RAM, 1TB Gen4 SSD, NVIDIA RTX 4070 8GB, 16-inch WQXGA 240Hz 500 nits HDR.",
      description: "The Lenovo Legion Pro 5i Gen 9 is engineered for esports champions and power users. Featuring Lenovo AI Engine+ with the LA1 AI chip to dynamically push max frame rates and efficiency.",
      specsJson: JSON.stringify({
        Processor: "Intel Core i9-14900HX (24 cores, 32 threads, up to 5.8 GHz)",
        Graphics: "NVIDIA GeForce RTX 4070 8GB GDDR6 (140W TGP)",
        Display: "16-inch WQXGA (2560x1600) IPS 240Hz, 100% sRGB, 500 nits",
        Memory: "32GB DDR5-5600MHz Dual-Channel",
        Storage: "1TB M.2 2280 PCIe 4.0x4 NVMe SSD",
        Battery: "80Wh with Super Rapid Charge Pro",
      }),
      images: [
        "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=800&auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=800&auto=format&fit=crop&q=80",
      ],
    },
    {
      name: "Jijau Apex Titan Custom Gaming PC Build",
      slug: "jijau-apex-titan-gaming-pc",
      sku: "JC-BUILD-TITAN-4080S",
      categorySlug: "custom-gaming-pcs",
      brandSlug: "corsair",
      price: 245000,
      salePrice: 229990,
      stock: 3,
      inStock: true,
      warranty: "3 Years Comprehensive Hardware Warranty & Lifetime Free Servicing",
      isFeatured: true,
      isBestseller: false,
      isNewArrival: true,
      isTrending: true,
      isGamingDeal: true,
      shortDesc: "Intel Core i7-14700K, RTX 4080 Super 16GB, 32GB DDR5 6000MHz RGB, 2TB Gen4 SSD, 360mm AIO Liquid Cooler.",
      description: "Hand-assembled and stress-tested in Pune by Jijau Computers master technicians. Features custom sleeved cables, ultra-clean cable routing, 360mm ARGB liquid cooler, and optimized airflow for extreme 4K gaming, Unreal Engine 5 rendering, and live streaming.",
      specsJson: JSON.stringify({
        Processor: "Intel Core i7-14700K (20 cores, 28 threads, up to 5.6 GHz)",
        Cooler: "DeepCool / Corsair 360mm ARGB Liquid AIO Cooler",
        Motherboard: "ASUS TUF Gaming Z790-PLUS WiFi DDR5",
        Graphics: "NVIDIA GeForce RTX 4080 Super 16GB GDDR6X",
        RAM: "Corsair Vengeance RGB 32GB (2x16GB) DDR5 6000MHz",
        Storage: "Samsung 990 PRO 2TB NVMe Gen4 SSD (7450 MB/s)",
        PSU: "Corsair RM850e 850W 80 Plus Gold ATX 3.0 Fully Modular",
        Cabinet: "Lian Li O11 Dynamic EVO RGB Panoramic Glass Case",
      }),
      images: [
        "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=800&auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop&q=80",
      ],
    },
    {
      name: "Jijau Creator Pro Workstation PC",
      slug: "jijau-creator-pro-workstation",
      sku: "JC-BUILD-CREATOR-9900X",
      categorySlug: "custom-gaming-pcs",
      brandSlug: "amd",
      price: 189000,
      salePrice: 174990,
      stock: 4,
      inStock: true,
      warranty: "3 Years Comprehensive Warranty with On-Site Assistance",
      isFeatured: true,
      isBestseller: true,
      isNewArrival: false,
      isTrending: true,
      isGamingDeal: false,
      shortDesc: "AMD Ryzen 9 7900X, RTX 4070 Ti Super 16GB, 64GB DDR5 RAM, 2TB SSD, High-End Workstation for Video & 3D.",
      description: "Designed specifically for architects, 4K/8K video editors (Premiere Pro, DaVinci Resolve), Blender 3D rendering, and Machine Learning workflows.",
      specsJson: JSON.stringify({
        Processor: "AMD Ryzen 9 7900X (12 Cores, 24 Threads, 5.6 GHz Max Boost)",
        Motherboard: "MSI MAG B650 TOMAHAWK WIFI",
        GPU: "ZOTAC / MSI GeForce RTX 4070 Ti Super 16GB",
        RAM: "Kingston Fury Beast 64GB (2x32GB) DDR5 5600MHz",
        Storage: "2TB Kingston KC3000 PCIe 4.0 NVMe SSD",
        PSU: "Cooler Master MWE 850W Gold V2",
        Case: "NZXT H7 Flow High Airflow Mid-Tower",
      }),
      images: [
        "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=800&auto=format&fit=crop&q=80",
      ],
    },
    {
      name: "Intel Core i7-14700K Desktop Processor",
      slug: "intel-core-i7-14700k-processor",
      sku: "INTEL-CPU-14700K",
      categorySlug: "processors",
      brandSlug: "intel",
      price: 39500,
      salePrice: 35990,
      stock: 15,
      inStock: true,
      warranty: "3 Years Intel India Authorized Warranty",
      isFeatured: true,
      isBestseller: true,
      isNewArrival: false,
      isTrending: true,
      isGamingDeal: false,
      shortDesc: "20 Cores (8 P-cores + 12 E-cores) & 28 Threads, LGA1700 Socket, up to 5.6 GHz Max Turbo Frequency.",
      description: "14th Gen Intel Core i7-14700K desktop processor with unlocked multiplier for overclocking. Features PCIe 5.0 & 4.0 support, DDR5 and DDR4 memory support, and integrated Intel UHD Graphics 770.",
      specsJson: JSON.stringify({
        "Total Cores": "20 (8 Performance + 12 Efficient)",
        "Total Threads": "28",
        "Max Turbo Frequency": "5.60 GHz",
        "Intel Smart Cache": "33 MB",
        Socket: "LGA1700",
        "Memory Support": "DDR5 5600 MT/s, DDR4 3200 MT/s",
        TDP: "125W Base / 253W Turbo",
      }),
      images: [
        "https://images.unsplash.com/photo-1555618568-9a3d4608c0ff?w=800&auto=format&fit=crop&q=80",
      ],
    },
    {
      name: "AMD Ryzen 7 7800X3D Gaming Processor",
      slug: "amd-ryzen-7-7800x3d-processor",
      sku: "AMD-CPU-7800X3D",
      categorySlug: "processors",
      brandSlug: "amd",
      price: 44000,
      salePrice: 38990,
      stock: 12,
      inStock: true,
      warranty: "3 Years AMD India Warranty",
      isFeatured: true,
      isBestseller: true,
      isNewArrival: false,
      isTrending: true,
      isGamingDeal: true,
      shortDesc: "The undisputed King of PC Gaming. 8 Cores, 16 Threads, 104MB Cache with AMD 3D V-Cache Technology.",
      description: "AMD Ryzen 7 7800X3D delivers record-shattering FPS in competitive and AAA games alike with colossal 96MB 3D V-Cache stacked directly onto the CCD.",
      specsJson: JSON.stringify({
        Cores: "8 Cores, 16 Threads",
        "Base Clock": "4.2 GHz / Boost up to 5.0 GHz",
        "L3 Cache": "96MB 3D V-Cache + 8MB L2 (104MB Total)",
        Socket: "AM5",
        "Memory Type": "DDR5 Dual Channel",
        TDP: "120W",
      }),
      images: [
        "https://images.unsplash.com/photo-1555618568-9a3d4608c0ff?w=800&auto=format&fit=crop&q=80",
      ],
    },
    {
      name: "MSI GeForce RTX 4070 Super 12GB Gaming X Slim",
      slug: "msi-geforce-rtx-4070-super-12gb",
      sku: "MSI-GPU-4070S-SLIM",
      categorySlug: "graphics-cards",
      brandSlug: "msi",
      price: 68500,
      salePrice: 62990,
      stock: 9,
      inStock: true,
      warranty: "3 Years MSI India Warranty",
      isFeatured: true,
      isBestseller: true,
      isNewArrival: true,
      isTrending: true,
      isGamingDeal: true,
      shortDesc: "12GB GDDR6X 192-bit, DLSS 3.5, Ada Lovelace Architecture, TRI FROZR 3 Thermal Design with TORX Fan 5.0.",
      description: "Supercharged gaming and AI creation with NVIDIA Ada Lovelace architecture, dedicated 4th Gen Tensor Cores and 3rd Gen RT Cores. Sleek slim form-factor designed for seamless compatibility.",
      specsJson: JSON.stringify({
        "CUDA Cores": "7168",
        Memory: "12GB GDDR6X",
        "Memory Bus": "192-bit",
        "Boost Clock": "2655 MHz",
        Outputs: "3x DisplayPort 1.4a, 1x HDMI 2.1a",
        "Recommended PSU": "650W",
      }),
      images: [
        "https://images.unsplash.com/photo-1591488320449-011701bb6704?w=800&auto=format&fit=crop&q=80",
      ],
    },
    {
      name: "ASUS ROG Swift OLED PG27AQDM 27-inch 240Hz Gaming Monitor",
      slug: "asus-rog-swift-oled-pg27aqdm-gaming-monitor",
      sku: "ASUS-MON-OLED-27",
      categorySlug: "monitors",
      brandSlug: "asus",
      price: 89900,
      salePrice: 79990,
      stock: 6,
      inStock: true,
      warranty: "3 Years ASUS India On-Site Warranty (Burn-In covered)",
      isFeatured: true,
      isBestseller: false,
      isNewArrival: true,
      isTrending: true,
      isGamingDeal: true,
      shortDesc: "27-inch QHD (2560x1440) OLED panel, 240Hz, 0.03ms GTG, 99% DCI-P3, Anti-glare micro-texture coating.",
      description: "Experience the ultimate visual clarity, pure inky blacks, and lightning fast 0.03ms response time with ASUS custom heatsink and intelligent voltage optimization for OLED longevity.",
      specsJson: JSON.stringify({
        "Screen Size": "26.5 Inch",
        "Panel Type": "OLED QHD 2560 x 1440",
        "Refresh Rate": "240 Hz",
        "Response Time": "0.03 ms (GTG)",
        "Color Gamut": "99% DCI-P3, 135% sRGB, Delta E < 2",
        "HDR Support": "HDR10 with 1000 nits Peak Brightness",
        Ports: "1x DisplayPort 1.4 (DSC), 2x HDMI 2.0, USB 3.2 Hub",
      }),
      images: [
        "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80",
      ],
    },
    {
      name: "Samsung 990 PRO 2TB NVMe M.2 PCIe Gen 4 SSD",
      slug: "samsung-990-pro-2tb-nvme-ssd",
      sku: "SAM-SSD-990PRO-2TB",
      categorySlug: "storage",
      brandSlug: "samsung",
      price: 21500,
      salePrice: 17490,
      stock: 20,
      inStock: true,
      warranty: "5 Years Samsung India Limited Warranty",
      isFeatured: false,
      isBestseller: true,
      isNewArrival: false,
      isTrending: true,
      isGamingDeal: false,
      shortDesc: "Read speeds up to 7,450 MB/s, Write speeds up to 6,900 MB/s with Samsung Nickel-coated controller.",
      description: "Reach near max performance of PCIe 4.0. The smart thermal controller delivers supreme power efficiency while maintaining blistering speeds for gaming, 3D modeling, and 4K editing.",
      specsJson: JSON.stringify({
        Capacity: "2 TB",
        Interface: "PCIe Gen 4.0 x4, NVMe 2.0",
        "Sequential Read": "Up to 7,450 MB/s",
        "Sequential Write": "Up to 6,900 MB/s",
        FormFactor: "M.2 2280",
        TBW: "1200 TBW",
      }),
      images: [
        "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800&auto=format&fit=crop&q=80",
      ],
    },
    {
      name: "Corsair Vengeance RGB 32GB (2x16GB) DDR5 6000MHz RAM",
      slug: "corsair-vengeance-rgb-32gb-ddr5-6000",
      sku: "COR-RAM-32GB-6000",
      categorySlug: "ram-memory",
      brandSlug: "corsair",
      price: 13500,
      salePrice: 10890,
      stock: 25,
      inStock: true,
      warranty: "Limited Lifetime Warranty",
      isFeatured: false,
      isBestseller: true,
      isNewArrival: false,
      isTrending: false,
      isGamingDeal: true,
      shortDesc: "Dual channel kit optimized for Intel XMP 3.0 & AMD EXPO, Dynamic ten-zone RGB lighting.",
      description: "Push the limits of your system with DDR5 memory, unlocking even faster frequencies, greater capacities, and better performance for cutting-edge platforms.",
      specsJson: JSON.stringify({
        "Memory Size": "32GB (2 x 16GB)",
        "Memory Type": "DDR5",
        "Tested Speed": "6000 MT/s",
        "Tested Latency": "CL36-36-36-76",
        "Tested Voltage": "1.35V",
        "RGB Lighting": "Dynamic Ten-Zone RGB with iCUE",
      }),
      images: [
        "https://images.unsplash.com/photo-1562976540-1502c2145186?w=800&auto=format&fit=crop&q=80",
      ],
    },
    {
      name: "Logitech G502 X PLUS Wireless RGB Gaming Mouse",
      slug: "logitech-g502-x-plus-wireless-mouse",
      sku: "LOG-MOU-G502X-PLUS",
      categorySlug: "gaming-accessories",
      brandSlug: "logitech",
      price: 15495,
      salePrice: 12995,
      stock: 14,
      inStock: true,
      warranty: "2 Years Logitech India Warranty",
      isFeatured: false,
      isBestseller: true,
      isNewArrival: true,
      isTrending: true,
      isGamingDeal: true,
      shortDesc: "LIGHTFORCE hybrid optical-mechanical switches, HERO 25K gaming sensor, LIGHTSYNC 8-LED RGB.",
      description: "The world's most popular gaming mouse icon, reinvented with LIGHTFORCE hybrid optical-mechanical switches, sub-micron HERO 25K sensor, and POWERPLAY wireless charging compatibility.",
      specsJson: JSON.stringify({
        Sensor: "HERO 25K (100 - 25,600 DPI)",
        Switches: "LIGHTFORCE Optical-Mechanical",
        "Battery Life": "Up to 120 hours (RGB off) / 37 hours (RGB on)",
        Weight: "106 grams",
        Connectivity: "LIGHTSPEED Wireless + USB-C",
      }),
      images: [
        "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop&q=80",
      ],
    },
    {
      name: "Dell G15 5530 Gaming Laptop (Intel i7-13650HX, RTX 4060)",
      slug: "dell-g15-5530-gaming-laptop",
      sku: "DELL-G15-4060",
      categorySlug: "laptops",
      brandSlug: "dell",
      price: 125000,
      salePrice: 109990,
      stock: 6,
      inStock: true,
      warranty: "1 Year Dell Onsite Hardware Warranty",
      isFeatured: true,
      isBestseller: true,
      isNewArrival: true,
      isTrending: true,
      isGamingDeal: true,
      shortDesc: "15.6-inch FHD 165Hz sRGB 100%, 13th Gen Intel Core i7-13650HX, 16GB DDR5, 1TB SSD, RTX 4060 8GB.",
      description: "Express your play style with the Dell G15 gaming laptop. High-performance thermal design with Alienware-inspired vapor chamber cooling.",
      specsJson: JSON.stringify({
        Processor: "Intel Core i7-13650HX",
        Graphics: "NVIDIA RTX 4060 8GB GDDR6 (140W)",
        Display: "15.6-inch FHD 165Hz 100% sRGB",
        RAM: "16GB DDR5 4800MHz",
        Storage: "1TB M.2 PCIe NVMe SSD",
      }),
      images: [
        "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=800&auto=format&fit=crop&q=80",
      ],
    },
    {
      name: "Dell Inspiron 15 3520 Core i5 12th Gen Laptop",
      slug: "dell-inspiron-15-3520-laptop",
      sku: "DELL-INSP-3520",
      categorySlug: "laptops",
      brandSlug: "dell",
      price: 58000,
      salePrice: 48990,
      stock: 12,
      inStock: true,
      warranty: "1 Year Dell India Warranty",
      isFeatured: false,
      isBestseller: true,
      isNewArrival: false,
      isTrending: false,
      isGamingDeal: false,
      shortDesc: "Intel Core i5-1235U, 16GB RAM, 512GB NVMe SSD, 15.6-inch 120Hz Display, Windows 11 + MS Office.",
      description: "A stylish everyday laptop designed to keep you connected and productive on the go with rapid express charging.",
      specsJson: JSON.stringify({
        Processor: "Intel Core i5-1235U (10 Cores, up to 4.4 GHz)",
        Display: "15.6-inch FHD 120Hz Anti-Glare",
        RAM: "16GB DDR4",
        Storage: "512GB NVMe SSD",
      }),
      images: [
        "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&auto=format&fit=crop&q=80",
      ],
    },
    {
      name: "HP Pavilion 15 (13th Gen Intel Core i5, 16GB RAM)",
      slug: "hp-pavilion-15-13th-gen",
      sku: "HP-PAV-15-I5",
      categorySlug: "laptops",
      brandSlug: "hp",
      price: 74990,
      salePrice: 66990,
      stock: 8,
      inStock: true,
      warranty: "1 Year HP Onsite Warranty",
      isFeatured: false,
      isBestseller: true,
      isNewArrival: false,
      isTrending: true,
      isGamingDeal: false,
      shortDesc: "13th Gen Intel Core i5-1335U, 16GB DDR4, 512GB SSD, 15.6-inch IPS FHD, B&O Audio.",
      description: "Sophisticated aluminum design with Bang & Olufsen tuned audio, precision touchpad, and vibrant IPS display.",
      specsJson: JSON.stringify({
        Processor: "Intel Core i5-1335U",
        RAM: "16GB DDR4-3200MHz",
        Storage: "512GB PCIe M.2 SSD",
        Audio: "Audio by B&O Dual Speakers",
      }),
      images: [
        "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&auto=format&fit=crop&q=80",
      ],
    },
    {
      name: "Apple MacBook Air 13.6-inch (M3 Chip, 16GB RAM, 512GB SSD)",
      slug: "apple-macbook-air-m3-13",
      sku: "APP-MBA-M3-512",
      categorySlug: "laptops",
      brandSlug: "apple",
      price: 134900,
      salePrice: 122990,
      stock: 5,
      inStock: true,
      warranty: "1 Year Apple Official Warranty",
      isFeatured: true,
      isBestseller: true,
      isNewArrival: true,
      isTrending: true,
      isGamingDeal: false,
      shortDesc: "Apple M3 8-core CPU, 10-core GPU, 13.6-inch Liquid Retina Display, up to 18 hours battery life, Midnight color.",
      description: "Lean, mean M3 machine. Incredibly portable and supercharged for fast multitasking, 4K ProRes editing, and AI workflows.",
      specsJson: JSON.stringify({
        Chip: "Apple M3 with 8-core CPU and 10-core GPU",
        Display: "13.6-inch Liquid Retina with True Tone (500 nits)",
        UnifiedMemory: "16GB",
        Storage: "512GB SSD",
        Battery: "Up to 18 hours wireless web",
      }),
      images: [
        "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80",
      ],
    },
    {
      name: "Apple iPhone 15 Pro 128GB (Natural Titanium)",
      slug: "apple-iphone-15-pro-128gb",
      sku: "APP-IP15P-128-NAT",
      categorySlug: "mobiles",
      brandSlug: "apple",
      price: 134900,
      salePrice: 124990,
      stock: 7,
      inStock: true,
      warranty: "1 Year Apple India Warranty",
      isFeatured: true,
      isBestseller: true,
      isNewArrival: true,
      isTrending: true,
      isGamingDeal: false,
      shortDesc: "A17 Pro chip, Aerospace-grade titanium, 48MP Pro camera system, Action button, USB-C with USB 3 speeds.",
      description: "iPhone 15 Pro forged in titanium with the groundbreaking A17 Pro chip and super-versatile pro camera system with 3x Telephoto.",
      specsJson: JSON.stringify({
        Processor: "A17 Pro chip (6-core CPU, 6-core GPU)",
        Display: "6.1-inch Super Retina XDR with ProMotion 120Hz",
        Camera: "48MP Main + 12MP Ultra Wide + 12MP 3x Telephoto",
        Port: "USB-C with USB 3 speeds (up to 10Gb/s)",
      }),
      images: [
        "https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=800&auto=format&fit=crop&q=80",
      ],
    },
    {
      name: "Samsung Galaxy S24 Ultra 5G (12GB RAM, 256GB, Titanium Gray)",
      slug: "samsung-galaxy-s24-ultra-5g",
      sku: "SAM-S24U-256-GRAY",
      categorySlug: "mobiles",
      brandSlug: "samsung",
      price: 129999,
      salePrice: 119999,
      stock: 6,
      inStock: true,
      warranty: "1 Year Samsung India Warranty with 1 Year S-Pen Cover",
      isFeatured: true,
      isBestseller: true,
      isNewArrival: true,
      isTrending: true,
      isGamingDeal: false,
      shortDesc: "Galaxy AI, Snapdragon 8 Gen 3 for Galaxy, 200MP Quad Telephoto Camera, Built-in S Pen, Titanium Frame.",
      description: "Welcome to the era of mobile AI with Galaxy AI. Circle to Search, Live Translate, and stunning 200MP detail with 100x Space Zoom.",
      specsJson: JSON.stringify({
        Processor: "Snapdragon 8 Gen 3 for Galaxy (4nm)",
        Display: "6.8-inch Dynamic AMOLED 2X QHD+ 120Hz (2600 nits)",
        Camera: "200MP + 50MP + 12MP + 10MP with 5x Optical / 100x Digital Zoom",
        Battery: "5000mAh with 45W Fast Charging",
      }),
      images: [
        "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80",
      ],
    },
    {
      name: "OnePlus 12 5G (16GB RAM, 512GB, Silky Black)",
      slug: "oneplus-12-5g-512gb",
      sku: "OP-12-16-512-BLK",
      categorySlug: "mobiles",
      brandSlug: "oneplus",
      price: 69999,
      salePrice: 64999,
      stock: 10,
      inStock: true,
      warranty: "1 Year OnePlus Official Warranty",
      isFeatured: true,
      isBestseller: true,
      isNewArrival: true,
      isTrending: true,
      isGamingDeal: true,
      shortDesc: "Snapdragon 8 Gen 3, 4th Gen Hasselblad Camera for Mobile, 5400mAh Battery, 100W SUPERVOOC Charging.",
      description: "OnePlus 12 delivers smooth beyond belief with Snapdragon 8 Gen 3, custom 2K 120Hz ProXDR display, and 100W wired + 50W wireless charging.",
      specsJson: JSON.stringify({
        Processor: "Snapdragon 8 Gen 3",
        RAM: "16GB LPDDR5X",
        Display: "6.82-inch 2K 120Hz ProXDR with Aqua Touch",
        Charging: "100W SUPERVOOC (0 to 100% in 26 mins)",
      }),
      images: [
        "https://images.unsplash.com/photo-1580910051074-3eb694886505?w=800&auto=format&fit=crop&q=80",
      ],
    },
    {
      name: "Epson EcoTank L3250 Wi-Fi All-in-One Ink Tank Printer",
      slug: "epson-ecotank-l3250-wifi-printer",
      sku: "EPS-L3250-WIFI",
      categorySlug: "printers",
      brandSlug: "epson",
      price: 17999,
      salePrice: 14999,
      stock: 14,
      inStock: true,
      warranty: "1 Year or 30,000 pages Epson India Onsite Warranty",
      isFeatured: true,
      isBestseller: true,
      isNewArrival: false,
      isTrending: true,
      isGamingDeal: false,
      shortDesc: "Print, Scan, Copy with Heat-Free Technology. Ultra-low cost per print (7 paise black, 18 paise color).",
      description: "Designed for business and home printing with Wi-Fi & Wi-Fi Direct. Seamlessly print from smart devices using Epson Smart Panel app.",
      specsJson: JSON.stringify({
        Type: "All-in-One Ink Tank (Print, Scan, Copy)",
        Speed: "Up to 33 ppm (Black), 15 ppm (Color)",
        Resolution: "5760 x 1440 dpi",
        Connectivity: "Wi-Fi, Wi-Fi Direct, USB 2.0",
      }),
      images: [
        "https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=800&auto=format&fit=crop&q=80",
      ],
    },
    {
      name: "Canon PIXMA MegaTank G3010 Wireless All-in-One Printer",
      slug: "canon-pixma-g3010-printer",
      sku: "CAN-PIX-G3010",
      categorySlug: "printers",
      brandSlug: "canon",
      price: 16500,
      salePrice: 13990,
      stock: 11,
      inStock: true,
      warranty: "1 Year Canon India Onsite Warranty",
      isFeatured: false,
      isBestseller: true,
      isNewArrival: false,
      isTrending: false,
      isGamingDeal: false,
      shortDesc: "High volume ink tank printing. Up to 6,000 pages black and 7,000 pages color per bottle set.",
      description: "Refillable ink tank wireless all-in-one printer for high volume printing at ultra-low cost with borderless photo printing.",
      specsJson: JSON.stringify({
        Functions: "Print, Scan, Copy",
        Yield: "6,000 pages (Black), 7,000 pages (Color)",
        Connectivity: "Wi-Fi, USB 2.0, Canon PRINT Inkjet/SELPHY App",
      }),
      images: [
        "https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=800&auto=format&fit=crop&q=80",
      ],
    },
    {
      name: "Brother DCP-L2520D Auto Duplex Laser Printer",
      slug: "brother-dcp-l2520d-laser-printer",
      sku: "BRO-DCP-L2520D",
      categorySlug: "printers",
      brandSlug: "brother",
      price: 19990,
      salePrice: 17490,
      stock: 8,
      inStock: true,
      warranty: "1 Year Brother India Onsite Warranty",
      isFeatured: false,
      isBestseller: false,
      isNewArrival: true,
      isTrending: true,
      isGamingDeal: false,
      shortDesc: "Monochrome Multi-Function Laser Printer with Automatic 2-Sided Printing, 30 ppm High Speed.",
      description: "Heavy-duty laser printer designed for offices, cyber cafes, and accounting firms requiring fast, crystal-clear 30ppm document printing.",
      specsJson: JSON.stringify({
        Type: "Monochrome Laser Multi-Function",
        PrintSpeed: "Up to 30 ppm",
        Duplex: "Automatic 2-Sided Printing",
        PaperTray: "250-sheet capacity",
      }),
      images: [
        "https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=800&auto=format&fit=crop&q=80",
      ],
    },
    {
      name: "CP PLUS 4MP Guard+ Smart Wi-Fi PT CCTV Camera",
      slug: "cp-plus-4mp-smart-wifi-pt-camera",
      sku: "CP-CAM-4MP-PT-WIFI",
      categorySlug: "cctv-camera",
      brandSlug: "cp-plus",
      price: 3800,
      salePrice: 2499,
      stock: 30,
      inStock: true,
      warranty: "2 Years CP PLUS Replacement Warranty",
      isFeatured: true,
      isBestseller: true,
      isNewArrival: true,
      isTrending: true,
      isGamingDeal: false,
      shortDesc: "4MP 2K Resolution, 360° Pan & Tilt, Motion Tracking, Two-Way Audio, Full Color Night Vision, Alexa Support.",
      description: "Protect your home, shop, or office with 360-degree pan-tilt coverage, AI human motion detection, and crisp two-way talk directly from your smartphone.",
      specsJson: JSON.stringify({
        Resolution: "4MP (2560 x 1440) 2K Quad HD",
        Rotation: "355° Pan & 90° Tilt",
        NightVision: "Full Color & IR up to 15 meters",
        Storage: "MicroSD up to 256GB + Cloud Storage",
        SmartFeatures: "AI Human Detection & Siren Alert",
      }),
      images: [
        "https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=800&auto=format&fit=crop&q=80",
      ],
    },
    {
      name: "Hikvision 4MP ColorVu Night Vision IP Dome Camera",
      slug: "hikvision-4mp-colorvu-ip-camera",
      sku: "HIK-CAM-4MP-COLORVU",
      categorySlug: "cctv-camera",
      brandSlug: "hikvision",
      price: 5200,
      salePrice: 3890,
      stock: 25,
      inStock: true,
      warranty: "3 Years Hikvision India Warranty",
      isFeatured: true,
      isBestseller: true,
      isNewArrival: false,
      isTrending: true,
      isGamingDeal: false,
      shortDesc: "24/7 Full Color imaging with F1.0 advanced lenses, PoE support, IP67 Weatherproof rating for outdoor security.",
      description: "Hikvision ColorVu technology captures vivid colorful images 24/7 in total darkness with F1.0 aperture super-sensors and supplemental warm LED lighting.",
      specsJson: JSON.stringify({
        Sensor: "1/1.8\" Progressive Scan CMOS 4MP",
        Lens: "2.8mm / 4mm fixed lens with F1.0 aperture",
        Protection: "IP67 Water and dust resistant",
        Power: "PoE (802.3af) or 12V DC",
      }),
      images: [
        "https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=800&auto=format&fit=crop&q=80",
      ],
    },
    {
      name: "TP-Link Tapo C210 Pan/Tilt 2K Smart Home Security Wi-Fi Camera",
      slug: "tp-link-tapo-c210-security-camera",
      sku: "TPL-CAM-TAPO-C210",
      categorySlug: "cctv-camera",
      brandSlug: "tp-link",
      price: 3299,
      salePrice: 2299,
      stock: 20,
      inStock: true,
      warranty: "2 Years TP-Link India Warranty",
      isFeatured: false,
      isBestseller: true,
      isNewArrival: false,
      isTrending: true,
      isGamingDeal: false,
      shortDesc: "2K 3MP Ultra HD, 360° Horizontal Range, Advanced Night Vision up to 30 ft, Sound & Light Alarm.",
      description: "Crystal clear 3MP high definition video, privacy mode to physically close the lens, and smart notifications whenever motion is detected.",
      specsJson: JSON.stringify({
        Resolution: "2K 3MP (2304 x 1296)",
        PanTilt: "360° Horizontal, 114° Vertical",
        Audio: "Two-Way Audio with built-in mic and speaker",
        App: "Tapo App for iOS & Android",
      }),
      images: [
        "https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=800&auto=format&fit=crop&q=80",
      ],
    },
  ];

  for (const p of products) {
    const categoryId = categoryMap.get(p.categorySlug) || "";
    const brandId = p.brandSlug ? brandMap.get(p.brandSlug) : null;

    const createdProduct = await prisma.product.upsert({
      where: { slug: p.slug },
      update: {
        price: p.price,
        salePrice: p.salePrice,
        stock: p.stock,
        isFeatured: p.isFeatured,
        isBestseller: p.isBestseller,
        isNewArrival: p.isNewArrival,
        isTrending: p.isTrending,
        isGamingDeal: p.isGamingDeal,
      },
      create: {
        name: p.name,
        slug: p.slug,
        sku: p.sku,
        description: p.description,
        shortDesc: p.shortDesc,
        price: p.price,
        salePrice: p.salePrice,
        stock: p.stock,
        inStock: p.inStock,
        warranty: p.warranty,
        isFeatured: p.isFeatured,
        isBestseller: p.isBestseller,
        isNewArrival: p.isNewArrival,
        isTrending: p.isTrending,
        isGamingDeal: p.isGamingDeal,
        specsJson: p.specsJson,
        categoryId: categoryId,
        brandId: brandId,
      },
    });

    // Add Images
    await prisma.productImage.deleteMany({ where: { productId: createdProduct.id } });
    for (let i = 0; i < p.images.length; i++) {
      await prisma.productImage.create({
        data: {
          url: p.images[i],
          isPrimary: i === 0,
          order: i,
          productId: createdProduct.id,
        },
      });
    }
  }

  // 8. Demo Service / Repair Request
  await prisma.serviceRequest.upsert({
    where: { ticketId: "JC-SRV-1001" },
    update: {},
    create: {
      ticketId: "JC-SRV-1001",
      customerName: "Rahul Deshmukh",
      phone: "9876543210",
      email: "rahul.deshmukh@gmail.com",
      deviceType: "Gaming Laptop",
      brand: "ASUS",
      model: "ROG Strix G15 (G513)",
      serialNo: "N7NRCX012398",
      issueDesc: "Laptop GPU fan making loud rattling noise and thermal throttling during games. Needs cleaning and thermal paste repasting.",
      status: "Repairing",
      adminNotes: "Fan replacement ordered from ASUS parts distributor. Thermal Grizzly Kryonaut applied. Running 3DMark stress test.",
      estimatedCost: 2800,
    },
  });

  await prisma.serviceRequest.upsert({
    where: { ticketId: "JC-SRV-1002" },
    update: {},
    create: {
      ticketId: "JC-SRV-1002",
      customerName: "Pooja Patil",
      phone: "9822334455",
      email: "pooja.patil@outlook.com",
      deviceType: "Desktop PC",
      brand: "Custom Assembled",
      model: "Ryzen 5 3600 PC",
      serialNo: "NA",
      issueDesc: "No display on monitor. Motherboard DRAM red LED is constantly lit up.",
      status: "Ready for Delivery",
      adminNotes: "Corrupted RAM stick in DIMM slot 2 replaced with new Kingston DDR4 8GB 3200MHz module. Display working normally.",
      estimatedCost: 2150,
    },
  });

  // 9. Demo Custom PC Request
  await prisma.customPcRequest.upsert({
    where: { reqNumber: "JC-RIG-8821" },
    update: {},
    create: {
      reqNumber: "JC-RIG-8821",
      customerName: "Aditya Shinde",
      phone: "9890112233",
      email: "aditya.shinde@techcorp.in",
      budget: "₹1,20,000 - ₹1,50,000",
      purpose: "Gaming & 4K Video Editing",
      cpuPref: "Intel Core i7 14th Gen",
      gpuPref: "NVIDIA RTX 4070 Super",
      ramPref: "32GB DDR5",
      storagePref: "1TB NVMe Gen4",
      cabinetPref: "White RGB Fish tank Case (Lian Li / Ant Esports)",
      notes: "Need 240Hz 1440p high FPS in Valorant, Cyberpunk 2077 and smooth DaVinci Resolve rendering.",
      status: "QUOTED",
      adminNotes: "Quotation sent over WhatsApp with ₹1,34,500 total including GST and 3 years on-site support.",
      totalEst: 134500,
    },
  });

  console.log("Database seeded successfully with Jijau Computers demo data!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
